version: "3.9"
networks:
  myAppNetwork:
    driver: bridge

services:
  postgresServerDb:
    container_name: container-postgres
    image: postgres:16.1
    ports:
      - "5022:5432"
    environment:
      - POSTGRES_USER=krot
      - POSTGRES_PASSWORD=p%rSDj4Imds07djc**dmUntdOidd3dZ_#WTi4B9Zo
      - POSTGRES_DB=WebApiStore
    networks:
      - myAppNetwork
    volumes:
        - /data/postgresql/data:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  app:
    container_name: asp_store_container
    image: olia1/asp-store-api
    ports:
      - "5817:8080"
    networks:
      - myAppNetwork
    depends_on:
      - postgresServerDb
    volumes:
     - /volumes/asp-store/images:/app/images
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
  
  client:
    container_name: store_client_container
    image: olia1/store-client
    ports:
      - "5145:80"
      

